name: odds_app
description: Edge Finder - apostas esportivas quantitativas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  share_plus: ^10.0.0
  pdf: ^3.11.0
  printing: ^5.13.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
